# Categories
CATEGORIES = [
    "AI Chatbots",
    "AI Image Generation",
    "AI Presentation",
    "AI Coding Assistance",
    "AI Meeting Notes",
    "AI Workflow Automation",
    "AI Knowledge Management",
    "AI Graphic Design"
]

# Catalog
TOOLS = [
    # Chatbots
    {"name":"ChatGPT","link":"https://chat.openai.com/","plan":"Free + Paid","logo":"https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg","category":"AI Chatbots","tags":["gpt","openai","chat"],"embeddable":False,"blurb":"General-purpose assistant with GPT models."},
    {"name":"Claude","link":"https://claude.ai/","plan":"Free + Paid","logo":"https://upload.wikimedia.org/wikipedia/commons/6/69/Anthropic_logo.svg","category":"AI Chatbots","tags":["anthropic","reasoning"],"embeddable":False,"blurb":"Helpful, reliable assistant by Anthropic."},
    {"name":"Gemini","link":"https://gemini.google.com/","plan":"Free + Paid","logo":"https://upload.wikimedia.org/wikipedia/commons/9/90/Google_Gemini_logo.svg","category":"AI Chatbots","tags":["google","multimodal"],"embeddable":False,"blurb":"Google’s multimodal AI chat."},
    {"name":"Perplexity","link":"https://www.perplexity.ai/","plan":"Free + Paid","logo":"https://upload.wikimedia.org/wikipedia/commons/3/3b/Perplexity_AI_logo.svg","category":"AI Chatbots","tags":["search","answers"],"embeddable":False,"blurb":"Answer engine with citations."},
    {"name":"Copilot","link":"https://copilot.microsoft.com/","plan":"Free + Paid","logo":"https://upload.wikimedia.org/wikipedia/commons/4/4f/Microsoft_Copilot_Icon.svg","category":"AI Chatbots","tags":["microsoft","office"],"embeddable":False,"blurb":"Assistant across Bing and Microsoft apps."},
    {"name":"Grok","link":"https://x.ai/","plan":"Paid","logo":"https://upload.wikimedia.org/wikipedia/commons/3/3a/Xai_logo.svg","category":"AI Chatbots","tags":["xai","x"],"embeddable":False,"blurb":"xAI chatbot with realtime knowledge."},

    # Image generation
    {"name":"Adobe Firefly","link":"https://www.adobe.com/products/firefly.html","plan":"Credits + Paid","logo":"https://upload.wikimedia.org/wikipedia/commons/5/5f/Adobe_Firefly_logo.svg","category":"AI Image Generation","tags":["generate","cc"],"embeddable":False,"blurb":"Generative AI inside Adobe ecosystem."},
    {"name":"DALL·E","link":"https://openai.com/dall-e-3","plan":"Paid","logo":"https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg","category":"AI Image Generation","tags":["images","openai"],"embeddable":False,"blurb":"Text-to-image via OpenAI."},
    {"name":"Midjourney","link":"https://www.midjourney.com/","plan":"Paid","logo":"https://upload.wikimedia.org/wikipedia/commons/0/09/Midjourney_Logo.png","category":"AI Image Generation","tags":["discord","art"],"embeddable":False,"blurb":"High-quality art generation on Discord."},

    # Presentations
    {"name":"Beautiful.ai","link":"https://www.beautiful.ai/","plan":"Paid","logo":"https://upload.wikimedia.org/wikipedia/commons/2/2f/Beautiful.ai_logo.svg","category":"AI Presentation","tags":["slides"],"embeddable":False,"blurb":"Design-first slide automation."},
    {"name":"Gamma","link":"https://gamma.app/","plan":"Free + Paid","logo":"https://assets.gamma.app/favicon-192.png","category":"AI Presentation","tags":["docs","decks"],"embeddable":True,"blurb":"Docs, decks, and pages with AI."},
    {"name":"Tome","link":"https://tome.app/","plan":"Free + Paid","logo":"https://tome.app/favicon.ico","category":"AI Presentation","tags":["narrative"],"embeddable":True,"blurb":"Narrative presentations generated by AI."},

    # Coding assistance
    {"name":"GitHub Copilot","link":"https://github.com/features/copilot","plan":"Paid","logo":"https://github.githubassets.com/images/modules/site/copilot/copilot-icon.svg","category":"AI Coding Assistance","tags":["code","editor"],"embeddable":False,"blurb":"AI pair programmer for IDEs."},
    {"name":"Cursor","link":"https://www.cursor.com/","plan":"Paid","logo":"https://www.cursor.com/favicon.ico","category":"AI Coding Assistance","tags":["ide","agent"],"embeddable":False,"blurb":"AI-native code editor."},
    {"name":"Tabnine","link":"https://www.tabnine.com/","plan":"Free + Paid","logo":"https://www.tabnine.com/favicon.ico","category":"AI Coding Assistance","tags":["autocomplete"],"embeddable":False,"blurb":"Code completion trained on permissive code."},

    # Meeting notes
    {"name":"Otter","link":"https://otter.ai/","plan":"Free + Paid","logo":"https://otter.ai/favicon.ico","category":"AI Meeting Notes","tags":["transcription","meetings"],"embeddable":True,"blurb":"Live transcription and summaries."},
    {"name":"Fireflies","link":"https://fireflies.ai/","plan":"Free + Paid","logo":"https://fireflies.ai/favicon.ico","category":"AI Meeting Notes","tags":["calls","notes"],"embeddable":True,"blurb":"AI notetaker for meetings."},

    # Workflow automation
    {"name":"Zapier","link":"https://zapier.com/","plan":"Free + Paid","logo":"https://zapier.com/favicon.ico","category":"AI Workflow Automation","tags":["automation","integrations"],"embeddable":True,"blurb":"Connect apps and automate workflows."},
    {"name":"Make","link":"https://www.make.com/","plan":"Free + Paid","logo":"https://www.make.com/favicon.ico","category":"AI Workflow Automation","tags":["scenarios","integrations"],"embeddable":True,"blurb":"Visual automation builder."},
    {"name":"n8n","link":"https://n8n.io/","plan":"Free (self-host) + Paid","logo":"https://n8n.io/favicon.ico","category":"AI Workflow Automation","tags":["self-host","node-based"],"embeddable":True,"blurb":"Open, fair-code automation platform."},

    # Knowledge management
    {"name":"Notion","link":"https://www.notion.so/","plan":"Free + Paid","logo":"https://upload.wikimedia.org/wikipedia/commons/e/e9/Notion-logo.svg","category":"AI Knowledge Management","tags":["notes","wiki"],"embeddable":True,"blurb":"All-in-one workspace with AI."},
    {"name":"Mem","link":"https://get.mem.ai/","plan":"Free + Paid","logo":"https://get.mem.ai/favicon.ico","category":"AI Knowledge Management","tags":["notes","memory"],"embeddable":True,"blurb":"AI-first notes and recall."},

    # Graphic design
    {"name":"Canva","link":"https://www.canva.com/","plan":"Free + Paid","logo":"https://static.canva.com/static/images/favicon.ico","category":"AI Graphic Design","tags":["design","templates"],"embeddable":True,"blurb":"Design anything with templates and AI."},
    {"name":"Microsoft Designer","link":"https://designer.microsoft.com/","plan":"Free + Paid","logo":"https://designer.microsoft.com/favicon.ico","category":"AI Graphic Design","tags":["image","layout"],"embeddable":True,"blurb":"AI design with quick prompts."},
]
